### ISSUE TITLE
Feature request: Correlation between the way you charge and battery health

### ISSUE THREAD

**Issue by Svec-Tomas** [CedricDeVijt/MacOS_Battery_Tracker#1]
Would it be possible to store also the charging history? For example yesterday it was charged from 10% to 80%, the day before from 30% to 100% and this has caused for example the battery health drop by 1%. Based on this data then to make some kind of correlation how is charging your laptop affecting the battery health? What kind of behaviour cause the battery health to drop. This would be super interesting in my opinion.

**Comment by CedricDeVijt** [comment]
Thank you for the suggestion! I agree that tracking the charging behaviour and correlating it with battery health would be interesting and insightful. However, the current design of MacOS Battery Tracker doesn't support this functionality.

The program is designed to be lightweight and doesn't run constantly in the background. It captures battery data at scheduled intervals (e.g., via a cron job), which means it can't track real-time charging behaviour. Implementing such a feature would require a different approach, with the program running continuously to monitor and log charging events in detail.

For now, the focus is on providing periodic snapshots of your battery's cycle count and maximum capacity, offering a balance between functionality and resource efficiency. I appreciate the feedback, and it's definitely something to consider for future iterations or a more advanced version of the tracker.

Thanks again for your input!
